### ISSUE TITLE
Round lineCap doesn't work for last line in path

### ISSUE THREAD

**Issue by anault** [e2d/e2d#10]
It renders the following:

![linecap](https://user-images.githubusercontent.com/6646230/28213800-a46e00b2-6875-11e7-924b-69f1ded22308.png)

Here's my render function:

```js
e2d.raf(() => {
	return e2d.render(
		e2d.clearRect(ctx.canvas.width, ctx.canvas.height),
		e2d.lineStyle({
			lineCap: "round",
			lineWidth: 50,
		},
			e2d.path(
				e2d.moveTo(100, 100),
				e2d.lineTo(200, 100),
				e2d.moveTo(100, 200),
				e2d.lineTo(200, 200),
				e2d.moveTo(100, 300),
				e2d.lineTo(200, 400),
			),
			e2d.stroke(),
		),
		cavasctx,
	);
});
```

**Comment by anault** [comment]
If I add to my lineStyle:
```js
lineDash: [20, 20],
```

I get the following:

![linecap2](https://user-images.githubusercontent.com/6646230/28213697-3845dafe-6875-11e7-8e8e-be7a27808436.png)

Line cap seems to work for the last line, but the line dash is ignored, weird.

**Comment by jtenner** [comment]
So lets see.

The problem is that you are closing the subpath with multiple lines, and the last line will always look werid.

Try this:
```javascript
let e2d = require('e2d');
let crel = require('crel');
let canvas;
crel(document.body, {}, canvas = crel('canvas', { width: 500, height: 500 }));
let ctx = canvas.getContext('2d');
e2d.raf(() => {
	return e2d.render(
		e2d.clearRect(canvas.width, canvas.height),
		e2d.lineStyle({
			lineCap: "round",
			lineWidth: 50,
		},
			
      e2d.beginPath(),
			e2d.moveTo(100, 100),
  		e2d.lineTo(200, 100),
      e2d.stroke(),
      e2d.beginPath(),
    	e2d.moveTo(100, 200),
      e2d.lineTo(200, 200),
      e2d.stroke(),
      e2d.beginPath(),
      e2d.moveTo(100, 300),
      e2d.lineTo(200, 400),
      e2d.stroke()
		),
		ctx
	);
});
```
Begin a new path for each line, just like you would in regular canvas.

![image](https://user-images.githubusercontent.com/3761339/28223484-930d138e-6899-11e7-894f-302b4c963491.png)

**Comment by anault** [comment]
Oh I see, thank you! Cool renderer you got there btw!

**Comment by jtenner** [comment]
Is there any chance I could direct message you about your usage of E2D? I'm always looking to improve my library and I was curious about how you used it.

Thanks for the compliment!
-Josh

**Comment by anault** [comment]
Sure, i'd be happy to help

**Comment by jtenner** [comment]
I can use telegram, facebook, discord... not sure what other services I have.  How can I reach you?

**Comment by anault** [comment]
I'll contact you over the [Gitter](https://gitter.im/e2d/e2d) when I get the time 👍
